"""empty message

Revision ID: 8d82acb6d7f1
Revises: 
Create Date: 2019-05-24 00:31:57.428029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d82acb6d7f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelo',
    sa.Column('idmodelo', sa.Integer(), nullable=False),
    sa.Column('nmmodelo', sa.String(), nullable=False),
    sa.Column('nmmetodoreferencia', sa.String(), nullable=False),
    sa.Column('tpinstrumento', sa.String(), nullable=False),
    sa.Column('dsmodelo', sa.String(), nullable=True),
    sa.Column('dtcriacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idmodelo'),
    sa.UniqueConstraint('nmmodelo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelo')
    # ### end Alembic commands ###
